### ISSUE TITLE
Torch7 Prototype Deep Q-Learning

### ISSUE THREAD

**Issue by wert23239** [wert23239/Meta-MarIO#34]
https://www.youtube.com/watch?v=V1eYniJ0Rnk

We need to get this to work on Windows:
But Linux will be easier first

**Comment by wert23239** [comment]
https://github.com/torch/torch7/wiki/Cheatsheet
https://github.com/kuz/DeepMind-Atari-Deep-Q-Learner/tree/master/dqn

**Comment by zhanwenchen** [comment]
Related:

https://github.com/torch/torch7/issues/293

**Comment by wert23239** [comment]
https://github.com/torch/paths/issues/9

## Alternative Cmake
@echo off
if "%1" == ".." if not "%2" == "-G" goto :G_NMake
cmake.exe %*
goto :EOF
:G_NMake
shift
cmake.exe .. -G "NMake Makefiles" %*
